### ISSUE TITLE
"Continue" button does not activate on 'Access' subform unless the Download or Compute "File" field is filled in

### ISSUE THREAD

**Issue by sarvagyaa** [chaineresearch/datastreams#6]
Kit: This morning I tried to publish an asset but in the second subform, after filling in the stream and docs URLs, the "Continue" button does not activate. Happens on both instances. Strange, because for @okpo.e, it worked yesterday.

**Comment by sarvagyaa** [comment]
I see this issue on localhost (branch: develop_sync) as well.

**Comment by kitblake** [comment]
This is fixed so I'm closing it, but there's a new related issue #13.

**Comment by sarvagyaa** [comment]
I still see this issue. @okpoEkpenyong, can you please recheck?
